### ISSUE TITLE
Bundle Does Not Work If Present Before First Start Of Opencast

### ISSUE THREAD

**Issue by lkiesow** [polimediaupv/paella-matterhorn#31]
If the paella JAR is put into the Opencast (Karaf) `deploy` folder before Opencast is started for the first time, the Paella player will not work. If it is put there during the runtime of Opencast, everything works as expected. This is possibly caused by a missing dependency which causes the paella bundle to be activated too early.

**Comment by lkiesow** [comment]
The behavior sounds very much like
http://karaf.922171.n3.nabble.com/Hot-deploy-priority-on-first-start-up-td4047948.html

**Comment by miesgre** [comment]
@lkiesow, I think this [1] solve this issue.
If so, maybe it can be PR to opencast. 

[1] https://groups.google.com/a/opencast.org/forum/#!msg/users/D0joq5Vr5js/7PZx8YzIAAAJ

**Comment by lkiesow** [comment]
The `felix.fileinstall.noInitialDelay = false` would cause an initial delay which then is hopefully long enough that it works. That should work, but is still a work-around.

The issue is more a Karaf issue than an Opencast issue and we should try to fix it there if possible. For going forward I would try updating Karaf (Next minor on OC 3.x next major on OC 4.x/develop) and check if the problem persists. If so, we should at least re-open [KARAF-4723](https://issues.apache.org/jira/browse/KARAF-4723) …and then maybe apply the work-around ;-D

**Comment by david-polymtl** [comment]
We have the same problem and the fix linked above didn't work for us. We didn't experiment with the settings yet however. In our case, this happens if you restart the Opencast service as well. Workaround solution is to stop the Opencast service, delete the .jar file in the Opencast deploy directory, start the Opencast service and copy a new .jar file to the deploy directory a few seconds after. As pointed out, player won't load if the service starts with the .jar file already in the deploy directory.

Using Opencast 3.2 and Paella 5.2.3

**Comment by karendolan** [comment]
@lkiesow can this issue be closed? 
Per [KARAF-4723](https://issues.apache.org/jira/browse/KARAF-4723) , the Karaf bug was fixed in Karaf 4.0.8. 
Per [MH-12742](https://opencast.jira.com/browse/MH-12742), Opencast is updated to Karaf 4.0.10 in develop (5.x)
Per [Merged pull on 4x](https://github.com/opencast/opencast/commit/4bbfb375aa6594856812eee3f120105fa85aa95c) Opencast 4x is updated to Karaf 4.0.9
Per [MH-12295 Update Karaf to 4.0.9 ](https://github.com/opencast/opencast/commit/01b9fd813ad143893acce7701b4fab35a34785fa) Opencast 3x is updated to Karaf 4.0.9

**Comment by lkiesow** [comment]
Not sure. Last I've heard, the problem still persisted (I think it was with 4.x).
Hence, you may need to actually test if this problem still persists.

**Comment by miesgre** [comment]
@lkiesow @karendolan The problem still persists in opencast 6.x. Should we apply the work-around in opencast?
